### Créer une réservation
POST http://localhost:8083/api/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTg3MDUxNywiZXhwIjoxNzQ1ODc0MTE3fQ._vozdIlc7oxzS57uSzHeSGWdbnCX2dlgsOzJCLl3HmY

{
  "travelerName": "Charlie",
  "destination": "Tokyo",
  "agencyName": "AgenceGamma"
}

### Lister toutes les réservations
GET http://localhost:8083/api/reservations

### Appeler Reservation sécurisé
GET http://localhost:8083/api/reservations
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTgzNzk5NSwiZXhwIjoxNzQ1ODQxNTk1fQ.v_PyMgITbVLJ8YykIaBVMM8vOM3IWXYjGdPSGrypZwQ