### Créer une réservation
POST http://localhost:8083/api/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NjgxNDkxMSwiZXhwIjoxNzQ2ODE4NTExfQ.EY1yPbKQegKDckQYyL9Max5ajGBaui24raCyptWZ87lEALv99Tt4pSELGWjo06ofBktMirkN3stG3dO9eaLXfEYwR5sCQDjLGCZQyCxi2k8jZL1myJD0kgqPxazrnt9SYW5HNcor3REhVuhhfO_JMAONZX2ZQUzxAr08ueCyRvzp7hddrm5nBD9DcVwc8HRzRSrSFP2bC9z7dr5TGxaTcsEa9K_YnUm_2aKq5K-75Q9J-zVom_LvasrZMlkXl4Mwrau8PGGNOiUDgxNzrc2NSx4DuYzlJ4krnvVext1lCNB5Pc76v3QEuixgWw2AQvAHefugYnS5_87UtFq-nWh2ZQ

{
  "travelerName": "Charlie",
  "destination": "Tokyo",
  "agencyName": "AgenceGamma"
}

### Lister toutes les réservations
GET http://localhost:8083/api/reservations

### Appeler Reservation sécurisé
GET http://localhost:8083/api/reservations
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NjgxNDkxMSwiZXhwIjoxNzQ2ODE4NTExfQ.EY1yPbKQegKDckQYyL9Max5ajGBaui24raCyptWZ87lEALv99Tt4pSELGWjo06ofBktMirkN3stG3dO9eaLXfEYwR5sCQDjLGCZQyCxi2k8jZL1myJD0kgqPxazrnt9SYW5HNcor3REhVuhhfO_JMAONZX2ZQUzxAr08ueCyRvzp7hddrm5nBD9DcVwc8HRzRSrSFP2bC9z7dr5TGxaTcsEa9K_YnUm_2aKq5K-75Q9J-zVom_LvasrZMlkXl4Mwrau8PGGNOiUDgxNzrc2NSx4DuYzlJ4krnvVext1lCNB5Pc76v3QEuixgWw2AQvAHefugYnS5_87UtFq-nWh2ZQ
