### Créer une réservation
POST http://localhost:8080/reservations/create
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg5MDE3NjYsImV4cCI6MTc0ODkwNTM2NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.oAIUwcoM9BtOz5vKkyPZ0Rxpwb6oAtH6FNa0R1Q_0dLXRYu_C-nGtL9sGihZghfGln7Bax7zts4YADoUQ7gEElkPynRufOpk2u92e7rLEoK8oyI0l62d16ixrIKv_3BlH2IBzFe3eMon-Vi-4-kmA9AmC--oDAt_iVr6HjIrr-0ljUF_pnwEliBdF-T7U-Uw572b5GqydLMlj2B0YPJXofjk_abg3LnINy_btTxyahZJsHyYtGQeWdzepPuZZn5uwpKjk2-fF-ZrwoST5AQkfeSSXTzntsrzU-VOiEWRzhhTF3mdFSSAc7zvjPIubEMjMy_dSjVZKeEwwnYJf2KRwA  

{
  "travelerName": "Charlie",
  "destination": "Tokyo",
  "agencyName": "AgenceGamma"
}

### Lister toutes les réservations
GET http://localhost:8080/reservations/list
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg5MDE3NjYsImV4cCI6MTc0ODkwNTM2NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIn0.oAIUwcoM9BtOz5vKkyPZ0Rxpwb6oAtH6FNa0R1Q_0dLXRYu_C-nGtL9sGihZghfGln7Bax7zts4YADoUQ7gEElkPynRufOpk2u92e7rLEoK8oyI0l62d16ixrIKv_3BlH2IBzFe3eMon-Vi-4-kmA9AmC--oDAt_iVr6HjIrr-0ljUF_pnwEliBdF-T7U-Uw572b5GqydLMlj2B0YPJXofjk_abg3LnINy_btTxyahZJsHyYtGQeWdzepPuZZn5uwpKjk2-fF-ZrwoST5AQkfeSSXTzntsrzU-VOiEWRzhhTF3mdFSSAc7zvjPIubEMjMy_dSjVZKeEwwnYJf2KRwA  
